upstream client {
    server client:3000; # We are basically saying; there is an upstream client. The server client is located at port 3000.
}

upstream api {
    server api:5000;
}

server {
    listen 80; # Listen on port 80

    # routing rules
    location / {
        proxy_pass http://client; # If anyone comes in with a request that has a '/', pass them forward to the upstream client 
    }

    location /api {
        rewrite /api/(.*) /$1 break; # Chop off the /api part of the url. 
        proxy_pass http://api; # Same as above.
    }

    # This is relevant for websockets that will be opened.
    location /ws {
      proxy_pass http://client;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
  }
}