FROM nginx

# The reason for the below copy is explained in docker hub for nginx image. We ask to take our default.conf and overwrite whatever default file there is with the same name
COPY ./default.conf /etc/nginx/conf.d/default.conf